### ISSUE TITLE
exploration.py -> pls use <if __name__ == "__main__":>

### ISSUE THREAD

**Issue by thegialeo** [Xenovortex/text-analytics-project#1]
Use <if \_\_name\_\_ == "\_\_main\_\_": >, to allow imports.

**Comment by kostraub** [comment]
müssen alle imports eigentlich auch innerhalb von if __name__ == "__main__": stehen oder kann ich die auch draußen bei den funktionen stehen haben? 

abgesehen von den imports ist jetzt alles unter if __name__ == "__main__":, hoffentlich funktioniert jetzt alles gut. Ich hab das mit den environments leider noch nicht hinbekommen UND ich hab was neues installiert, ich hoffe das sorgt nicht für probleme. das package das ich installiert hab war openpyxl (zum lesen von excel-dateien)

**Comment by dennlinger** [comment]
Ganz im Gegenteil, die Imports sollten eigentlich **nie innerhalb** von `name == "__main__"` stehen.
Das Konstrukt ist dazu gedacht, dass bei Ausführung des *Skripts* (versus Ausführung als Modul) eine bestimmte Aktion ausgeführt wird. Die Mehrheit eurer Files sollte eigentlich auch gar keine solchen Main-Funktionen haben und mehr als Modulstruktur aufgebaut sein.

**Comment by thegialeo** [comment]
Sry, wenn es unklar war. Die Reihenfolge sollte sein: 1) import der packages 2) Definition der Funktionen 3) if \_\_name\_\_ == "\_\_main\_\_" 4) alles was ausführung ist oder etwas macht kommt innerhalb if \_\_name\_\_ == "\_\_main\_\_"

**Comment by thegialeo** [comment]
Das erlaubt mir exploration.py zu importieren und die funktionen zu benutzen statt es selbst nochmal zu implementieren

**Comment by kostraub** [comment]
> Ganz im Gegenteil, die Imports sollten eigentlich **nie innerhalb** von `name == "__main__"` stehen.
> Das Konstrukt ist dazu gedacht, dass bei Ausführung des _Skripts_ (versus Ausführung als Modul) eine bestimmte Aktion ausgeführt wird. Die Mehrheit eurer Files sollte eigentlich auch gar keine solchen Main-Funktionen haben und mehr als Modulstruktur aufgebaut sein.

Habs dann auch gemerkt als VS Code die imports automatisch nach oben teleportiert hat als ich sie in die main gepastet hab 😂 die main ist im moment hauptsächlich da um zu probieren ob die funktionen das machen was sie sollen, passt das so?

> Das erlaubt mir exploration.py zu importieren und die funktionen zu benutzen statt es selbst nochmal zu implementieren

Jo hab das gestern abend noch so geändert, kann man jetzt alles machen

**Comment by thegialeo** [comment]
Das mit der environment können wir noch bis zum nächsten Meeting aufschieben. Erstmal sich daran gewöhnen git zu benutzen. Im Pipfile ist sowieso noch python 3.7 festgelegt und wir sollen nochmal diskutiern ob wir nicht vielleicht die neuste python version nehmen wollen (hatten ja festgestellt, dass wir alle verschiedene versionen haben). zumindest müssen alle die gleiche python version wie im Pipfile haben, damit jeder die environment aktivieren kann.

**Comment by thegialeo** [comment]
Vielleicht hab ich das im letzten Meeting zu schnell erklärt, aber die Schritte um das Package auf der Environment zu installieren wäre:
1) cd zum Projekt folder (wo Pipfile und Pipfile.lock ist)
2) install pipenv, wenn du das noch nicht gemacht hast (pip install pipenv)
3) install packages die in Pipfile aufgelistet sind mit pipenv install (es sind eh noch nicht so viele dependencies, hauptsächlich die test packages die die tutoren aufgesetzt haben)
4) activate environment (pipenv shell)
5) install openpyxl to environment (pipenv install openpyxl) oder wenn das package nach deployment nicht gebraucht wird, sondern nur zur entwicklung der software kannst du auch direkt auf dev installieren mit pipenv install openpyxl --dev (in dem Fall macht es eher weniger sinn, ich nehme an du brauchst das zum Einlesen von daten)

**Comment by thegialeo** [comment]
Da du VSCode benutzt: https://code.visualstudio.com/docs/python/environments

**Comment by thegialeo** [comment]
Brauch seine Zeit sich daran zu gewöhnen mit git und virtual environment. in ein paar wochen können wir dann nochmal über testing und documentation des codes sprechen und wie man eine documentation aus dem codes generiert (angenommen man hat "richtig" kommentiert). Also das was ich am ende noch kurz vorgeführt hatte mit den zwei beispiel files.

**Comment by thegialeo** [comment]
Das mit dem branching hast du aber verstanden oder? Wir können nochmal discord, wenn es unklar ist. Ich frag nur weil du noch als einziger keinen eigenen branch hast.

**Comment by kostraub** [comment]
also kommentiert habe ich, denke ich, bisher richtig für die documentation. 

ich dachte ich hätte das branching verstanden aber scheinbar doch nicht. also ich bin auf dem master, mach git pull, geh auf konrad-dev, mach git merge master, gibt keine probleme, ich geh auf master, mach git merge konrad-dev, und mach dann git push. offenbar ist das nicht richtig weil bei mir immer noch kein branch steht, welcher teil war falsch?  

bin die ganze zeit im discord, ping mich einfach und ich geh in den vc.

kennst du dich mit dem linting aus? ich weiß nicht so richtig warum mein code failt, irgendwas daran findet es wohl geschmacklos geschrieben.

**Comment by thegialeo** [comment]
ah, dann hast du es verstanden. ist alles richtig so kannst du es auch machen. wenn du willst das dein branch konrad-dev auch auf github erscheint, kannst du zusätzlich wenn du auf konrad-dev bist push machen (sozusagen 2-mal push).

**Comment by thegialeo** [comment]
zum linting kann jetzt so aus der ferne nichts sagen ohne es genauer anschaut zu haben

**Comment by thegialeo** [comment]
ich glaube das issue ist gelöst, ich würde es dann schließen. du kannst ja ein neues issue für das linting aufmachen, wenn du willst. vllt wenn du den code vom jupyter notebook in ein python file kopierst, versucht vscode die cells zu erhalten und setzt marker, damit du in vscode die cells immernoch einzeln ausführen kannst. das ist jetzt einfach ein schuss ins schwarze, könnte auch voll daneben sein
