### ISSUE TITLE
dataset location

### ISSUE THREAD

**Issue by thegialeo** [Xenovortex/text-analytics-project#2]
I think it is better to have a separate folder for the dataset and the folder src should only contain the source code. This will make it easier to just run pdoc on the src folder and get the documentation from the source code only. But that is something we can discuss in a meeting. For the time being, we can just leave it as it is. I will create a Trello card for that under Meeting Topics.

**Comment by kostraub** [comment]
ist mir im grunde egal aber was passiert denn im moment wenn man pdoc laufen lässt, versucht es ne documentation für die excel-datei zu machen? ich find src/data eigentlich schon ganz nett aber kann man natürlich ändern

**Comment by thegialeo** [comment]
meiner meinung macht es mehr sinn es im separaten folder zu haben (hab das jetzt auch so implementiert, dass in einen separaten folder automatisch downloaded wird). src steht ja eigentlich abgekürzt für source code, da sollte auch nur source code rein. du kannst in der folder hierachy hochspringen mit os.path.dirname
